### ISSUE TITLE
Questions regarding the re-animation

### ISSUE THREAD

**Issue by cao-kais** [Iven-Wu/CASA#2]
Hi,

Thanks for the great work!

As described in the paper, the _re-animation_ optimizes the joint angles of each bone for the skeletal shape, or the rigid transform for control point-based shape to minimize the Chamfer Distance between the reference shape and the predicted shape. 

I was wondering how this is achieved for LASR and ViSER as these two methods rely on 2D observations (images, optical flow etc.) instead of directly optimizing to fit a target 3D shape. Could you provide more details on the procedure to do re-animation for LASR and ViSER in the paper? Thanks!

**Comment by Iven-Wu** [comment]
For re-animation we utilize 3D supervision, directly optimizing the chamfer distance between the predicted shape and reference ground-truth shape. We do not use any 2D observation in this setting.  All three methods (CASA, LASR, ViSER) have the predictions of 3D shape at each iteration, which can be used for computing chamfer distances.

**Comment by cao-kais** [comment]
So during the optimization, the chamfer distance is used as the only loss function to fit the 3D shape? Just to confirm that my understanding is correct, this means that for LASR and ViSER, the canonical shape and blend skinning weights are fixed, while the control points are the only parameters being updated and optimized to fit the target 3D shape using chamfer distance as the loss?

**Comment by Iven-Wu** [comment]
Yes. The only difference is that for LASR/ViSER, the updated parameters are control points, while for CASA is the rotation angle for bones.

**Comment by cao-kais** [comment]
I see. Thank you so much for the clarification!
