### ISSUE TITLE
.npz discrepancy test_animal

### ISSUE THREAD

**Issue by BastiaanGroot** [Iven-Wu/CASA#3]
Hi,

I have an issue when running python main.py -c config/real_world.yaml
After running the clip_retrieve.py, the retrieval animal is correctly set.
However, after constructing the `data_utils.Optimization_data()` object, the `.npz` and `.png` files are loaded for the `test_animal`.
This is rather strange as we have as input of the `test_animal` the Annotations and JPEGImages from DAVIS, and thus no `.npz` files.

I'd hope to recieve clarification regarding this.

Thanks

**Comment by Iven-Wu** [comment]
Thank you for your questions. 

Right now we only provide the code for synthetic animals. So the code loads .npz files from the dataset and the .npz file contains information such as optical flow, segmentation, etc.. 

For the DAVIS dataset or any other real-world datasets, you will need to use other models to calculate all those information. 

And for real-world cases, only the PNG and mesh shapes are used during the process, image for retrieval and mesh for init shape.

**Comment by BastiaanGroot** [comment]
Thank you for the quick response, I have been working on replicating the results proposed in the paper using the DAVIS dataset. Can I maybe contact you in private for some questions regarding this?

**Comment by Iven-Wu** [comment]
Sure. You may send it to my gmail, ***@***.***

Bastiaan Groot ***@***.***> 于2024年6月20日周四 03:39写道：

**Comment by Iven-Wu** [comment]
Sure. You can find my personal email on my homepage.
